on:
  push:
    branches: [master]
  pull_request:

name: CI

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Cache
        uses: actions/cache@v2
        with:
          path: ${{ github.workspace }}/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - uses: actions/setup-node@v1
        with:
          node-version: "12"
      - run: yarn install --frozen-lockfile
      - name: Lint
        uses: mooyoul/tslint-actions@v1.1.1
        with:
          pattern: '*.ts'
          token: ${{ secrets.GITHUB_TOKEN }}
      - run: yarn build
        env:
            CI: true
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out
