on:
  push:
    branches: [master]
  pull_request:

name: CI

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "12"
      - run: yarn install
      - name: eslint
        uses: icrawl/action-eslint@v1
      - run: yarn build
