on:
  push:
    branches: [master]
  pull_request:

name: CI

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "12"
      - run: yarn install
      - name: Lint
        uses: mooyoul/tslint-actions@v1.1.1
        with:
          pattern: '*.ts'
          token: ${{ secrets.GITHUB_TOKEN }}
      #- run: yarn build
